import 'dart:async';
import 'dart:io';

import 'package:camera/camera.dart';
import 'package:flutter/foundation.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:path_provider/path_provider.dart';
import 'package:record/record.dart';
import '../services/gesture_service.dart';
import '../services/gemma_service.dart';
import '../services/stt_service.dart';
import '../services/model_manager.dart';
import '../services/tts_service.dart';
import '../services/sibi_alphabet_service.dart';
import '../services/bisindo_alphabet_service.dart';
import '../services/persistence_service.dart';
import '../../shared/models/conversation_entry.dart';
import '../../shared/models/user_persona.dart';

/// Detection modes for sign-to-text.
///   sign          — BISINDO gesture recognition (LSTM, 30-frame recording)
///   sibiAlphabet  — SIBI alphabet (1 hand, real-time)
///   bisindoAlphabet — BISINDO alphabet (2 hands, real-time)
enum DetectionMode { sign, sibiAlphabet, bisindoAlphabet }

// ---- Deaf to Hearing State ----

class DeafToHearingState {
  final List<String> currentGloss;
  final String refinedSentence;
  final String? aiSuggestion;
  /// Contextual Empathy tips (bullet points) — generated by Gemma 4
  /// setelah refineGloss, muncul di bawah hasil terjemahan.
  final List<String> empathyTips;
  final bool isCapturing;
  final bool isProcessing;
  /// 98-dim nose-centered model input features for debug visualization.
  final List<double> modelInputFeatures;
  final String? errorMessage;
  /// Per-sign recording: elapsed milliseconds since recording started.
  final int bufferProgress;
  /// Per-sign recording: total target duration in milliseconds (default 3000).
  final int bufferTotalMs;
  /// True while recording one sign (timer-driven, default 3s window).
  final bool isRecordingSign;
  /// Current detection mode: sign gestures, SIBI alphabet, or BISINDO alphabet.
  final DetectionMode detectionMode;
  /// Live alphabet letter currently detected (alphabet mode only).
  final String? currentAlphabetLetter;
  /// Alphabet vote progress: 0.0 → 1.0 toward commit threshold.
  final double alphabetVoteProgress;

  const DeafToHearingState({
    this.currentGloss = const [],
    this.refinedSentence = '',
    this.aiSuggestion,
    this.empathyTips = const [],
    this.isCapturing = false,
    this.isProcessing = false,
    this.modelInputFeatures = const [],
    this.errorMessage,
    this.bufferProgress = 0,
    this.bufferTotalMs = 3000,
    this.isRecordingSign = false,
    this.detectionMode = DetectionMode.sign,
    this.currentAlphabetLetter,
    this.alphabetVoteProgress = 0.0,
  });

  DeafToHearingState copyWith({
    List<String>? currentGloss,
    String? refinedSentence,
    String? aiSuggestion,
    List<String>? empathyTips,
    bool? isCapturing,
    bool? isProcessing,
    List<double>? modelInputFeatures,
    String? errorMessage,
    bool clearAiSuggestion = false,
    bool clearEmpathyTips = false,
    int? bufferProgress,
    int? bufferTotalMs,
    bool? isRecordingSign,
    DetectionMode? detectionMode,
    String? currentAlphabetLetter,
    bool clearAlphabetLetter = false,
    double? alphabetVoteProgress,
  }) {
    return DeafToHearingState(
      currentGloss: currentGloss ?? this.currentGloss,
      refinedSentence: refinedSentence ?? this.refinedSentence,
      aiSuggestion: clearAiSuggestion ? null : (aiSuggestion ?? this.aiSuggestion),
      empathyTips: clearEmpathyTips ? const [] : (empathyTips ?? this.empathyTips),
      isCapturing: isCapturing ?? this.isCapturing,
      isProcessing: isProcessing ?? this.isProcessing,
      modelInputFeatures: modelInputFeatures ?? this.modelInputFeatures,
      errorMessage: errorMessage,
      bufferProgress: bufferProgress ?? this.bufferProgress,
      bufferTotalMs: bufferTotalMs ?? this.bufferTotalMs,
      isRecordingSign: isRecordingSign ?? this.isRecordingSign,
      detectionMode: detectionMode ?? this.detectionMode,
      currentAlphabetLetter:
          clearAlphabetLetter ? null : (currentAlphabetLetter ?? this.currentAlphabetLetter),
      alphabetVoteProgress: alphabetVoteProgress ?? this.alphabetVoteProgress,
    );
  }
}

final deafToHearingProvider =
    StateNotifierProvider<DeafToHearingNotifier, DeafToHearingState>((ref) {
  return DeafToHearingNotifier(ref);
});

class DeafToHearingNotifier extends StateNotifier<DeafToHearingState> {
  DeafToHearingNotifier(this._ref) : super(const DeafToHearingState());

  final Ref _ref;
  final _gestureService = GestureService();
  final _gemmaService = GemmaService();
  final _ttsService = TtsService();
  final _sibiService = SibiAlphabetService();
  final _bisindoAbcService = BisindoAlphabetService();

  bool _isProcessingFrame = false;
  bool _isRefining = false;
  bool _isFrontCamera = true;

  // Alphabet mode: majority vote over last N frames before committing a letter.
  final _alphabetVoteBuffer = <String?>[];
  static const _voteWindowSize = 30;
  static const _voteThreshold = 20; // 20/30 frames must agree (~2s hold)
  DateTime? _lastLetterCommitTime;
  static const _commitCooldown = Duration(milliseconds: 2000);

  /// Initialize gesture services (model + MediaPipe) and alphabet services.
  Future<void> initializeServices() async {
    debugPrint('[DeafToHearing] Initializing GestureService...');
    try {
      await _gestureService.initialize();
      debugPrint('[DeafToHearing] LSTM loaded: ${_gestureService.isModelLoaded}');
    } catch (e, st) {
      debugPrint('[DeafToHearing] GestureService FAILED: $e\n$st');
    }

    debugPrint('[DeafToHearing] Initializing SibiAlphabetService...');
    try {
      await _sibiService.initialize();
      debugPrint('[DeafToHearing] SIBI loaded: ${_sibiService.isLoaded}');
    } catch (e, st) {
      debugPrint('[DeafToHearing] SibiAlphabetService FAILED: $e\n$st');
    }

    debugPrint('[DeafToHearing] Initializing BisindoAlphabetService...');
    try {
      await _bisindoAbcService.initialize();
      debugPrint('[DeafToHearing] BISINDO-ABC loaded: ${_bisindoAbcService.isLoaded}');
    } catch (e, st) {
      debugPrint('[DeafToHearing] BisindoAlphabetService FAILED: $e\n$st');
    }
  }

  /// Switch between sign gesture mode, SIBI alphabet, or BISINDO alphabet.
  void switchDetectionMode(DetectionMode mode) {
    if (state.detectionMode == mode) return;
    if (state.isRecordingSign) {
      _gestureService.cancelSignRecording();
    }
    _alphabetVoteBuffer.clear();
    _lastLetterCommitTime = null;
    state = state.copyWith(
      detectionMode: mode,
      isRecordingSign: false,
      bufferProgress: 0,
      clearAlphabetLetter: true,
      errorMessage: null,
    );
    debugPrint('[DeafToHearing] Switched to ${mode.name} mode');
  }

  /// Whether current mode is any alphabet mode.
  bool get _isAlphabetMode =>
      state.detectionMode == DetectionMode.sibiAlphabet ||
      state.detectionMode == DetectionMode.bisindoAlphabet;

  /// Called every camera frame. Only runs when capturing.
  void onCameraFrame(dynamic cameraImage, double previewW, double previewH,
      {int sensorOrientation = 90, bool isFrontCamera = true}) {
    if (!state.isCapturing || _isProcessingFrame) return;
    _isFrontCamera = isFrontCamera;
    _isProcessingFrame = true;

    if (_isAlphabetMode) {
      _processAlphabetFrame(cameraImage as CameraImage, sensorOrientation);
    } else {
      _gestureService
          .addFrameFromCameraAsync(cameraImage, sensorOrientation)
          .then((_) {
        if (!mounted) return;
        _isProcessingFrame = false;
        // Update debug panel with latest 98-dim features
        final modelInput = _gestureService.lastRawFeaturesForDebug;
        state = state.copyWith(modelInputFeatures: modelInput);
      }).catchError((e) {
        _isProcessingFrame = false;
        debugPrint('[DeafToHearing] Frame error: $e');
      });
    }
  }

  void _processAlphabetFrame(CameraImage frame, int sensorOrientation) {
    // Route to correct alphabet service based on mode
    String? detectedLetter;
    if (state.detectionMode == DetectionMode.sibiAlphabet) {
      final result = _sibiService.detectFromCameraImage(
          frame, sensorOrientation, _isFrontCamera);
      detectedLetter = result?.letter;
    } else {
      final result = _bisindoAbcService.detectFromCameraImage(
          frame, sensorOrientation, _isFrontCamera);
      detectedLetter = result?.letter;
    }
    _isProcessingFrame = false;

    if (!mounted) return;

    // Update vote buffer
    _alphabetVoteBuffer.add(detectedLetter);
    if (_alphabetVoteBuffer.length > _voteWindowSize) {
      _alphabetVoteBuffer.removeAt(0);
    }

    // Always update live feedback + vote progress
    // Compute how close the leading letter is to the commit threshold.
    double voteProgress = 0.0;
    if (_alphabetVoteBuffer.isNotEmpty) {
      final counts = <String, int>{};
      for (final l in _alphabetVoteBuffer) {
        if (l != null) counts[l] = (counts[l] ?? 0) + 1;
      }
      if (counts.isNotEmpty) {
        final topCount = counts.values.reduce((a, b) => a > b ? a : b);
        voteProgress = (topCount / _voteThreshold).clamp(0.0, 1.0);
      }
    }

    state = state.copyWith(
      currentAlphabetLetter: detectedLetter,
      clearAlphabetLetter: detectedLetter == null,
      alphabetVoteProgress: voteProgress,
    );

    // Need full window before committing
    if (_alphabetVoteBuffer.length < _voteWindowSize) return;

    // Cooldown check
    final now = DateTime.now();
    if (_lastLetterCommitTime != null &&
        now.difference(_lastLetterCommitTime!) < _commitCooldown) {
      return;
    }

    // Majority vote
    final counts = <String, int>{};
    for (final l in _alphabetVoteBuffer) {
      if (l != null) counts[l] = (counts[l] ?? 0) + 1;
    }
    if (counts.isEmpty) return;

    final top = counts.entries.reduce((a, b) => a.value > b.value ? a : b);
    if (top.value < _voteThreshold) return;

    // Commit the stable letter
    _alphabetVoteBuffer.clear();
    _lastLetterCommitTime = now;

    final newGloss = [...state.currentGloss, top.key];
    debugPrint(
        '[DeafToHearing] [ABC] Committed: ${top.key} (${top.value}/$_voteWindowSize) → [${newGloss.join("")}]');
    state = state.copyWith(
      currentGloss: newGloss,
      errorMessage: null,
      alphabetVoteProgress: 0.0,
    );
  }

  // ── Session lifecycle ────────────────────────────────────────────────────

  /// Enter gesture session: enables MediaPipe + camera stream.
  void startCapture() {
    if (!_gestureService.isModelLoaded) {
      state = state.copyWith(
        errorMessage: 'Model belum dimuat. Restart halaman ini.',
      );
      return;
    }
    state = state.copyWith(
      isCapturing: true,
      currentGloss: [],
      refinedSentence: '',
      errorMessage: null,
      bufferProgress: 0,
      isRecordingSign: false,
      clearAiSuggestion: true,
      clearEmpathyTips: true,
    );
    _gestureService.startGestureCapture();
  }

  /// Exit gesture session.
  void stopCapture() {
    _gestureService.stopGestureCapture();
    state = state.copyWith(
      isCapturing: false,
      isRecordingSign: false,
      bufferProgress: 0,
      isProcessing: false,
    );
  }

  /// Start recording ONE sign — records for 3s then auto-predicts.
  /// Call on button press.
  void startSignRecording() {
    if (!state.isCapturing || state.isRecordingSign) return;
    state = state.copyWith(
      isRecordingSign: true,
      bufferProgress: 0,
      errorMessage: null,
    );
    _gestureService.startSignRecording(
      durationMs: 3000,
      onSignDetected: _onSignDetected,
      onProgress: (elapsedMs, totalMs) {
        if (!mounted) return;
        state = state.copyWith(
          bufferProgress: elapsedMs,
          bufferTotalMs: totalMs,
        );
      },
    );
    debugPrint('[DeafToHearing] startSignRecording');
  }

  /// Cancel current sign recording (e.g. user released button early).
  void cancelSignRecording() {
    if (!state.isRecordingSign) return;
    _gestureService.cancelSignRecording();
    state = state.copyWith(isRecordingSign: false, bufferProgress: 0);
  }

  void _onSignDetected(GestureResult result) {
    if (!mounted) return;

    state = state.copyWith(
      isRecordingSign: false,
      bufferProgress: 0,
    );

    if (result.labelIndex < 0) {
      // No confident prediction
      debugPrint('[DeafToHearing] Sign not recognized (low confidence)');
      state = state.copyWith(errorMessage: 'Isyarat tidak dikenali. Coba lagi.');
      return;
    }

    final newGloss = [...state.currentGloss, result.word];
    debugPrint(
      '[DeafToHearing] Sign: ${result.word} '
      '(${(result.confidence * 100).toStringAsFixed(1)}%) '
      '→ gloss=[${newGloss.join("|").toUpperCase()}]',
    );
    state = state.copyWith(currentGloss: newGloss, errorMessage: null);
  }

  // ── AI finalization ──────────────────────────────────────────────────────

  /// Send accumulated gloss list to Gemma for refinement.
  Future<void> sendToAI() async {
    final glossList = List<String>.from(state.currentGloss);
    if (glossList.isEmpty) {
      state = state.copyWith(errorMessage: 'Belum ada isyarat yang direkam.');
      return;
    }
    await _refineCurrentGloss(glossList);
  }

  /// Delete the last committed word from gloss.
  void removeLastWord() {
    if (state.currentGloss.isEmpty) return;
    final trimmed = state.currentGloss.sublist(0, state.currentGloss.length - 1);
    state = state.copyWith(
      currentGloss: trimmed,
      refinedSentence: '',
      errorMessage: null,
    );
  }

  /// Clear all gloss words.
  void clearGloss() {
    state = state.copyWith(
      currentGloss: [],
      refinedSentence: '',
      errorMessage: null,
      clearAiSuggestion: true,
      clearEmpathyTips: true,
    );
  }

  /// Add a space separator (alphabet mode: separate words).
  void addSpace() {
    final newGloss = [...state.currentGloss, ' '];
    state = state.copyWith(currentGloss: newGloss);
  }

  Future<void> _refineCurrentGloss(List<String> gloss) async {
    if (_isRefining) return;
    _isRefining = true;
    state = state.copyWith(
        isProcessing: true, clearAiSuggestion: true, clearEmpathyTips: true);
    try {
      final cleanedGloss = _cleanGlossForInference(gloss);
      debugPrint(
        '[DeafToHearing] Sending to Gemma: [${cleanedGloss.join(" | ")}]',
      );

      final sentence = await _gemmaService.refineGloss(cleanedGloss);
      if (mounted) {
        state = state.copyWith(refinedSentence: sentence, isProcessing: false);
      }

      // Simpan ke riwayat percakapan
      if (sentence.isNotEmpty) {
        final entry = ConversationEntry(
          id: DateTime.now().millisecondsSinceEpoch.toString(),
          sourcePersona: UserPersona.tuli,
          originalText: cleanedGloss.join(' '),
          translatedText: sentence,
          timestamp: DateTime.now(),
          type: ConversationType.signToText,
        );
        _ref.read(conversationHistoryProvider.notifier).addEntry(entry);
        debugPrint('[DeafToHearing] Saved to history: ${entry.id}');
      }

      if (mounted && sentence.isNotEmpty && gloss.length > 1) {
        // Generate Contextual Empathy — bullet-point tips for hearing user.
        final tips = await _gemmaService.getEmpathyTips(sentence);
        if (mounted && tips.isNotEmpty) {
          state = state.copyWith(
            empathyTips: tips,
            // Keep legacy aiSuggestion as first tip for backward compatibility
            aiSuggestion: tips.first,
          );
        } else {
          // Fallback ke single-sentence jika tips kosong
          final suggestion = await _gemmaService.getEmpathySuggestion(sentence);
          if (mounted && suggestion != null && suggestion.isNotEmpty) {
            state = state.copyWith(aiSuggestion: suggestion);
          }
        }
      }
    } finally {
      _isRefining = false;
    }
  }

  List<String> _cleanGlossForInference(List<String> gloss) {
    final cleaned = <String>[];
    for (final rawToken in gloss) {
      final token = rawToken.trim();
      if (token.isEmpty || token == '?') continue;
      final normalized = token.toUpperCase();
      final last = cleaned.isNotEmpty ? cleaned.last.toUpperCase() : null;
      if (normalized == last) continue;
      cleaned.add(token);
    }
    return cleaned;
  }

  Future<void> speakSentence() async {
    if (state.refinedSentence.isNotEmpty) {
      await _ttsService.speak(state.refinedSentence);
    }
  }

  @override
  void dispose() {
    _gestureService.stopGestureCapture();
    super.dispose();
  }
}

// ---- Hearing to Deaf State ----

class HearingToDeafState {
  final String rawTranscription;
  final String smartSummary;
  final bool isRecording;
  final bool isProcessing;
  final String? errorMessage;
  final String? lastRecordingPath;
  final String? debugWavInfo;

  const HearingToDeafState({
    this.rawTranscription = '',
    this.smartSummary = '',
    this.isRecording = false,
    this.isProcessing = false,
    this.errorMessage,
    this.lastRecordingPath,
    this.debugWavInfo,
  });

  HearingToDeafState copyWith({
    String? rawTranscription,
    String? smartSummary,
    bool? isRecording,
    bool? isProcessing,
    String? errorMessage,
    String? lastRecordingPath,
    String? debugWavInfo,
  }) {
    return HearingToDeafState(
      rawTranscription: rawTranscription ?? this.rawTranscription,
      smartSummary: smartSummary ?? this.smartSummary,
      isRecording: isRecording ?? this.isRecording,
      isProcessing: isProcessing ?? this.isProcessing,
      errorMessage: errorMessage,
      lastRecordingPath: lastRecordingPath ?? this.lastRecordingPath,
      debugWavInfo: debugWavInfo ?? this.debugWavInfo,
    );
  }
}

final hearingToDeafProvider =
    StateNotifierProvider<HearingToDeafNotifier, HearingToDeafState>((ref) {
  return HearingToDeafNotifier(ref);
});

class HearingToDeafNotifier extends StateNotifier<HearingToDeafState> {
  HearingToDeafNotifier(this._ref) : super(const HearingToDeafState());
  final Ref _ref;

  final _sttService = SttService();
  final _gemmaService = GemmaService();
  final _recorder = AudioRecorder();
  String? _recordingPath;

  /// Start recording real audio via microphone.
  Future<void> startRecording() async {
    state = state.copyWith(
      isRecording: true,
      rawTranscription: '',
      smartSummary: '',
      errorMessage: null,
    );

    try {
      // Whisper reload tidak perlu — Gemma 4 audio encoder adalah primary.
      // Whisper hanya di-load saat fallback (jika Gemma audio gagal).

      // Check permission
      final hasPermission = await _recorder.hasPermission();
      if (!hasPermission) {
        state = state.copyWith(
          isRecording: false,
          errorMessage: 'Izin mikrofon ditolak',
        );
        return;
      }

      // Record WAV: 16kHz, 16-bit, mono — Whisper expected format
      final tempDir = await getTemporaryDirectory();
      _recordingPath = '${tempDir.path}/stt_recording.wav';

      await _recorder.start(
        RecordConfig(
          encoder: AudioEncoder.wav,
          sampleRate: 16000,
          numChannels: 1,
          bitRate: 256000,
        ),
        path: _recordingPath!,
      );

      debugPrint('[STT] Recording started → $_recordingPath');
    } catch (e) {
      debugPrint('[STT] Recording start error: $e');
      state = state.copyWith(
        isRecording: false,
        errorMessage: 'Gagal merekam: $e',
      );
    }
  }

  /// Stop recording, transcribe, then summarize.
  Future<void> stopRecording() async {
    state = state.copyWith(isRecording: false, isProcessing: true);

    try {
      // Stop recorder — file is saved at _recordingPath
      final path = await _recorder.stop();
      debugPrint('[STT] Recording stopped → $path');

      final audioPath = path ?? _recordingPath;
      if (audioPath == null || audioPath.isEmpty) {
        state = state.copyWith(
          isProcessing: false,
          errorMessage: 'Rekaman gagal disimpan',
        );
        return;
      }

      // Check file exists
      final file = File(audioPath);
      if (!await file.exists()) {
        state = state.copyWith(
          isProcessing: false,
          errorMessage: 'File rekaman tidak ditemukan',
        );
        return;
      }

      final fileSize = await file.length();
      debugPrint('[STT] Audio file: $audioPath ($fileSize bytes)');

      // Inspect WAV header for debugging
      String wavInfo = 'File: $fileSize bytes';
      try {
        final headerBytes = await file.openRead(0, 44).fold<List<int>>(
          <int>[], (prev, chunk) => prev..addAll(chunk));
        if (headerBytes.length >= 44) {
          final bd = ByteData.sublistView(Uint8List.fromList(headerBytes));
          final sampleRate = bd.getUint32(24, Endian.little);
          final numChannels = bd.getUint16(22, Endian.little);
          final bitsPerSample = bd.getUint16(34, Endian.little);
          final dataSize = bd.getUint32(40, Endian.little);
          final durationSec = dataSize / (sampleRate * numChannels * (bitsPerSample / 8));
          wavInfo = '${sampleRate}Hz ${numChannels}ch ${bitsPerSample}bit | '
              '${durationSec.toStringAsFixed(1)}s | ${fileSize}B';
          debugPrint('[STT] WAV: $wavInfo');
        }
      } catch (e) {
        debugPrint('[STT] WAV header parse error: $e');
      }

      if (mounted) {
        state = state.copyWith(
          lastRecordingPath: audioPath,
          debugWavInfo: wavInfo,
        );
      }

      // [EKSPERIMEN] Gemma 4 audio transcription — dispose Whisper dulu biar Gemma punya full RAM.
      // Jika gagal/kosong, reload Whisper dan fallback ke pipeline biasa.
      String transcription = '';
      bool usedGemmaAudio = false;

      if (_gemmaService.isLoaded) {
        // Free Whisper RAM dulu sebelum Gemma audio
        debugPrint('[STT] [GEMMA-AUDIO] Disposing Whisper to free RAM for Gemma audio...');
        await _sttService.dispose();

        try {
          final audioFile = File(audioPath);
          final rawBytes = await audioFile.readAsBytes();
          // Strip WAV header (44 bytes) — kirim raw PCM saja ke Gemma audio encoder
          Uint8List pcmData = rawBytes.length > 44 ? rawBytes.sublist(44) : rawBytes;

          // Downsample hanya jika PCM terlalu besar — cegah OOM pada audio panjang di Pixel 6a.
          // 256KB ≈ 8s pada 16kHz 16-bit mono. Audio normal (<8s) dikirim penuh 16kHz.
          const pcmSafeLimit = 256 * 1024; // 256 KB
          if (pcmData.length > pcmSafeLimit) {
            final before = pcmData.length;
            pcmData = _downsamplePcm16Bit(pcmData);
            debugPrint('[STT] [GEMMA-AUDIO] Downsampled ${before}B → ${pcmData.length}B (OOM guard)');
          }
          if (pcmData.length > pcmSafeLimit) {
            final before = pcmData.length;
            pcmData = _downsamplePcm16Bit(pcmData);
            debugPrint('[STT] [GEMMA-AUDIO] 2nd downsample ${before}B → ${pcmData.length}B');
          }

          debugPrint('[STT] [GEMMA-AUDIO] Trying Gemma 4 audio (${pcmData.length} PCM bytes)...');

          final gemmaResult = await _gemmaService.transcribeAudio(pcmData);
          debugPrint('[STT] [GEMMA-AUDIO] Result length: ${gemmaResult.length} chars');

          if (gemmaResult.isNotEmpty) {
            transcription = gemmaResult;
            usedGemmaAudio = true;
            debugPrint('[STT] [GEMMA-AUDIO] SUCCESS — using Gemma audio transcription');
          } else {
            debugPrint('[STT] [GEMMA-AUDIO] Empty result — falling back to Whisper');
          }
        } catch (e) {
          debugPrint('[STT] [GEMMA-AUDIO] Failed: $e — falling back to Whisper');
        }
      }

      // Fallback: Whisper STT (jika Gemma audio gagal/kosong)
      if (!usedGemmaAudio) {
        // Cek dulu apakah Whisper model tersedia (opsional, tidak wajib download)
        final whisperReady = await ModelManager().isModelReady(ModelType.whisperSTT);
        if (whisperReady) {
          if (!_sttService.isLoaded) {
            debugPrint('[STT] [FALLBACK] Loading Whisper...');
            await _sttService.initialize();
          }
          debugPrint('[STT] [FALLBACK] Transcribing via Whisper...');
          transcription = await _sttService.transcribeFile(audioPath);
          debugPrint('[STT] [FALLBACK] Whisper result length: ${transcription.length} chars');
        } else {
          debugPrint('[STT] [FALLBACK] Whisper not downloaded — no fallback available');
        }
      }

      if (transcription.isEmpty) {
        state = state.copyWith(
          isProcessing: false,
          rawTranscription: '',
          errorMessage: 'Transkripsi kosong ($wavInfo)',
        );
        return;
      }

      if (mounted) {
        state = state.copyWith(rawTranscription: transcription);
      }

      // Unload Whisper jika masih loaded — model swap untuk hemat RAM sebelum Gemma simplify.
      if (_sttService.isLoaded) {
        debugPrint('[STT] Unloading Whisper to free RAM before Gemma...');
        await _sttService.dispose();
      }

      // Step 2: Simplify via Gemma 4 for Deaf user
      // Jika pakai Gemma audio, bisa skip simplify (sudah 1 model) — tapi tetap run untuk konsistensi.
      debugPrint('[STT] Simplifying via Gemma...');
      final summary = await _gemmaService.simplifyForDeaf(transcription);
      debugPrint('[STT] Simplified length: ${summary.length} chars');

      if (mounted) {
        state = state.copyWith(
          smartSummary: summary,
          isProcessing: false,
        );
      }

      // Simpan ke history setelah pipeline selesai
      if (transcription.isNotEmpty) {
        final entry = ConversationEntry(
          id: DateTime.now().millisecondsSinceEpoch.toString(),
          sourcePersona: UserPersona.mendengar,
          originalText: transcription,
          translatedText: summary.isNotEmpty ? summary : transcription,
          timestamp: DateTime.now(),
          type: ConversationType.speechToSign,
        );
        _ref.read(conversationHistoryProvider.notifier).addEntry(entry);
        debugPrint('[STT] Saved to history: ${entry.id}');
      }
    } catch (e) {
      debugPrint('[STT] Pipeline error: $e');
      if (mounted) {
        state = state.copyWith(
          isProcessing: false,
          errorMessage: 'Error: $e',
        );
      }
    }
  }

  @override
  void dispose() {
    _recorder.dispose();
    super.dispose();
  }
}

/// Downsample 16-bit mono PCM dengan averaging 2 sample berurutan.
/// Input/output: raw PCM bytes (int16 little-endian, no WAV header).
/// Hasilnya setengah panjang — efektif 2× speed dari perspektif Gemma audio encoder.
/// Speech tetap intelligible karena formant utama (<4kHz) terjaga.
Uint8List _downsamplePcm16Bit(Uint8List pcm) {
  final bd = ByteData.sublistView(pcm);
  final inSamples = pcm.length ~/ 2;
  final outSamples = inSamples ~/ 2;
  final out = ByteData(outSamples * 2);
  for (int i = 0; i < outSamples; i++) {
    final s1 = bd.getInt16(i * 4, Endian.little);
    final s2 = bd.getInt16(i * 4 + 2, Endian.little);
    final avg = ((s1 + s2) >> 1).clamp(-32768, 32767);
    out.setInt16(i * 2, avg, Endian.little);
  }
  return out.buffer.asUint8List();
}

// ---- Conversation History ----

final conversationHistoryProvider =
    StateNotifierProvider<ConversationHistoryNotifier, List<ConversationEntry>>(
        (ref) {
  return ConversationHistoryNotifier();
});

class ConversationHistoryNotifier
    extends StateNotifier<List<ConversationEntry>> {
  ConversationHistoryNotifier() : super([]) {
    _load();
  }

  final PersistenceService _svc = PersistenceService.instance;

  void _load() {
    final raw = _svc.loadConversations();
    state = raw
        .map((m) => ConversationEntry.fromJson(Map<String, dynamic>.from(m)))
        .toList();
  }

  Future<void> addEntry(ConversationEntry entry) async {
    await _svc.addConversation(entry.id, entry.toJson());
    state = [entry, ...state];
  }

  Future<void> removeEntry(String id) async {
    await _svc.deleteConversation(id);
    state = state.where((e) => e.id != id).toList();
  }

  Future<void> clearAll() async {
    await _svc.clearConversations();
    state = [];
  }
}
